//! Parity test against the golden corpus generated by the Java reference
//! implementation (see rust/dev/DumpGolden.java): every language of the
//! official cldr-plurals.json x every probe value. The Java side is itself
//! verified against the official CLDR data with zero deviations, so parity
//! here implies CLDR conformance of the Rust port.

use lalein::{PluralResolver, PluralType};

#[test]
fn rust_resolvers_match_java_golden_corpus() {
    let corpus = include_str!("../../../corpus/cldr-golden.csv");
    let mut checked = 0usize;
    let mut mismatches = Vec::new();
    for line in corpus.lines() {
        let mut parts = line.split(';');
        let lang = parts.next().unwrap();
        let value: f64 = parts.next().unwrap().parse().unwrap();
        let expected = match parts.next().unwrap() {
            "ZERO" => PluralType::Zero,
            "ONE" => PluralType::One,
            "TWO" => PluralType::Two,
            "FEW" => PluralType::Few,
            "MANY" => PluralType::Many,
            "OTHER" => PluralType::Other,
            other => panic!("unknown category {other}"),
        };
        let resolver = if lang == "pt-PT" {
            PluralResolver::for_locale("pt", "PT")
        } else {
            PluralResolver::for_language(lang)
        };
        let actual = resolver.find_type(value).unwrap_or(PluralType::Other);
        if actual != expected {
            mismatches.push(format!("{lang} n={value} expected={expected:?} got={actual:?}"));
        }
        checked += 1;
    }
    assert!(checked > 60_000, "corpus looks truncated: {checked} rows");
    assert!(mismatches.is_empty(), "{} mismatches:\n{}", mismatches.len(), mismatches.join("\n"));
}
