//! `lalein` — proper i18n plurals with full CLDR conformance and a tiny
//! footprint. Rust port of the Java library.
//!
//! * Every language of the official `cldr-plurals.json` is covered — the
//!   [`plural`] module is verified against a golden corpus generated by the
//!   exhaustively CLDR-verified Java implementation.
//! * Zero dependencies. Backends (JSON, YAML, …) are opt-in cargo features,
//!   so you only pay for what you enable.
//!
//! ```
//! use lalein::{Arg, Lalein, Parameter, Translation};
//!
//! let mut lalein = Lalein::new(vec![(
//!     "apples".to_string(),
//!     Translation {
//!         format: "%{main}".to_string(),
//!         parameters: vec![(
//!             "main".to_string(),
//!             Parameter {
//!                 argument_index: 1,
//!                 one: Some("I have an apple.".to_string()),
//!                 other: "I have %d apples.".to_string(),
//!                 ..Default::default()
//!             },
//!         )],
//!     },
//! )]);
//! lalein.set_plural_resolver(lalein::PluralResolver::for_language("en"));
//!
//! assert_eq!(lalein.format("apples", &[Arg::Int(1)]).unwrap(), "I have an apple.");
//! assert_eq!(lalein.format("apples", &[Arg::Int(5)]).unwrap(), "I have 5 apples.");
//! ```

pub mod plural;
mod engine;
mod printf;

pub use engine::{Arg, Lalein, LaleinError, Parameter, Translation};
pub use plural::{PluralResolver, PluralType};
