package lalein

// Parity test against the golden corpus generated by the Java reference
// implementation (see rust/dev/DumpGolden.java): every language of the
// official cldr-plurals.json x every probe value. The Java side is itself
// verified against the official CLDR data with zero deviations, so parity
// here implies CLDR conformance of the Go port.

import (
	"os"
	"strconv"
	"strings"
	"testing"
)

func TestGoResolversMatchJavaGoldenCorpus(t *testing.T) {
	data, err := os.ReadFile("../corpus/cldr-golden.csv")
	if err != nil {
		t.Fatalf("cannot read golden corpus: %v", err)
	}
	want := map[string]PluralType{
		"ZERO": PluralZero, "ONE": PluralOne, "TWO": PluralTwo,
		"FEW": PluralFew, "MANY": PluralMany, "OTHER": PluralOther,
	}
	checked := 0
	for _, line := range strings.Split(strings.TrimSpace(string(data)), "\n") {
		parts := strings.Split(line, ";")
		if len(parts) != 3 {
			t.Fatalf("malformed corpus line: %q", line)
		}
		value, err := strconv.ParseFloat(parts[1], 64)
		if err != nil {
			t.Fatalf("malformed value in %q: %v", line, err)
		}
		var resolver PluralResolver
		if parts[0] == "pt-PT" {
			resolver = UsingLocale("pt", "PT")
		} else {
			resolver = UsingLanguage(parts[0])
		}
		category, ok := resolver.FindType(value)
		if !ok {
			category = PluralOther
		}
		if category != want[parts[2]] {
			t.Errorf("%s n=%s: expected %s, got %s", parts[0], parts[1], parts[2], category)
		}
		checked++
	}
	if checked < 60000 {
		t.Fatalf("corpus looks truncated: %d rows", checked)
	}
}
